server:
  port: 8081
spring:
  security:
    oauth2:
      client:
        provider:
          # 인가서버 기동이 필요
          springOAuth2:
            issuer-uri: http://localhost:9000
            authorization-uri: http://localhost:9000/oauth2/authorize  # 임시코드  code 발급
            jwk-set-uri: http://localhost:9000/oauth2/jwks  # 토큰 검증시 공개키
            token-uri: http://localhost:9000/oauth2/token # 토큰
            user-info-uri: http://localhost:9000/userinfo # 사용자정보
            #user-name-attribute: preferred_username
        registration:
          springOAuth2:
            authorization-grant-type: authorization_code
            client-id: oauth2-client-app1
            client-name: oauth2-client-app
            client-secret: secret1
            redirect-uri: http://127.0.0.1:8081/login/oauth2/code/springoauth2
            #scope: openid,read,write
            scope: openid,read,write,photo,friend